"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var persona_1 = require("./persona");
var direccion_1 = require("./direccion");
var mail_1 = require("./mail");
var telefono_1 = require("./telefono");
var primeraResidenciaMaria = new direccion_1.Direccion("Calle Maria 1", 3, 4, "B", 28056, "Madrid", "Madrid");
var segundaResidenciaMaria = new direccion_1.Direccion("Calle Maria 2", 4, false, false, 28085, "Valencia", "Valencia");
var mailMaria = new mail_1.Mail("personal", "maria@gmail.com");
var telefonoFijoMaria = new telefono_1.Telefono("fijo", 916435654);
var telefonoMovilMaria = new telefono_1.Telefono("movil", 654893267);
var datosMaria = new persona_1.Persona('María', 'García Fernández', 26, '50478907H', new Date(1997, 5, 11), 'naranja', 'mujer', [primeraResidenciaMaria, segundaResidenciaMaria], [mailMaria], [telefonoFijoMaria, telefonoMovilMaria], "En verano vive en su segunda residencia");
var primeraResidenciaAntonio = new direccion_1.Direccion("Calle Antonio 1", 29, 1, "A", 60578, "Valencia", "Valencia");
var segundaResidenciaAntonio = new direccion_1.Direccion("Calle Antonio 2", 9, 6, "B", 694256, "Gandía", "Valencia");
var mailPersonalAntonio = new mail_1.Mail("personal", "antonio@hotmail.com");
var mailTrabajoAntonio = new mail_1.Mail("personal", "Antonio78@gmail.com");
var telefonoFijoAntonio = new telefono_1.Telefono("fijo", 916554389);
var telefonoMovilAntonioPersonal = new telefono_1.Telefono("movil", 689542688);
var datosAntonio = new persona_1.Persona('Antonio', 'González Gutiérrez', 37, '50873490T', new Date(1986, 4, 20), 'negro', 'hombre', [primeraResidenciaAntonio, segundaResidenciaAntonio], [mailPersonalAntonio, mailTrabajoAntonio], [telefonoFijoAntonio, telefonoMovilAntonioPersonal], "En verano alquila su segunda residencia");
var primeraResidenciaJorge = new direccion_1.Direccion("Calle Jorge 1", 20, 9, "C", 69844, "Sevilla", "Sevilla");
var segundaResidenciaJorge = new direccion_1.Direccion("Calle Jorge 2", 4, 4, "A", 79056, "Córdoba", "Córdoba");
var mailPersonalJorge = new mail_1.Mail("personal", "Jorge@gmail.com");
var telefonoFijoJorge = new telefono_1.Telefono("fijo", 916552895);
var telefonoMovilJorge = new telefono_1.Telefono("movil", 697437756);
var datosJorge = new persona_1.Persona('Jorge', 'Hernán Jiménez', 58, '50762877R', new Date(1964, 8, 9), 'azul', 'hombre', [primeraResidenciaJorge, segundaResidenciaJorge], [mailPersonalJorge], [telefonoFijoJorge, telefonoMovilJorge], "Pasa los fines de semana en la segunda residencia");
console.log("Contactos antes del cambio:");
console.log(datosMaria);
console.log(datosAntonio);
console.log(datosJorge);
var agenda = new Array(datosMaria, datosAntonio, datosJorge);
var dniABuscar = "50478907H";
var personaAEditar = agenda.find(function (persona) { return persona.dni === dniABuscar; });
var nuevaDireccion = new direccion_1.Direccion("Calle Fátima", 96, 1, "A", 38076, "Bilbao", "Vizcaya");
var nuevoMail = new mail_1.Mail("trabajo", "reclutamiento.smart@gmail.com");
var nuevoTelefono = new telefono_1.Telefono("fijo", 915679634);
personaAEditar.agregarNuevaDireccion(nuevaDireccion);
personaAEditar.agregarNuevoMail(nuevoMail);
personaAEditar.agregarNuevoTelefono(nuevoTelefono);
console.log("Contactos después del cambio:");
console.log(datosMaria);
console.log(datosAntonio);
console.log(datosJorge);
